### ISSUE TITLE
现在trocr最大的问题就是这个384*384的预处理

### ISSUE THREAD

**Issue by archwolf118** [chineseocr/trocr-chinese#3]
超长文本resize到384*384抽特征，似乎不太合理，但是经过验证后tocr也能给出一个较为正确的结果。
不知道各位大佬怎么看？可能用padding会更好一点。

**Comment by wenlihaoyu** [comment]
为啥不合理？只要你的文本不是太长（比如宽度超过2048）。padding不就浪费了，为啥不选用其他图像侧的backbone呢？

**Comment by archwolf118** [comment]
resize到固定尺寸必然会导致文字信息产生变形。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lywen ***@***.***&gt;
发送时间: 2022年4月9日 21:19
收件人: chineseocr/trocr-chinese ***@***.***&gt;
抄送: archwolf118 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [chineseocr/trocr-chinese] 现在trocr最大的问题就是这个384*384的预处理 (Issue #3)





 
为啥不合理？只要你的文本不是太长（比如宽度超过2048）。padding不就浪费了，为啥不选用其他图像侧的backbone呢？

**Comment by 746891300** [comment]
我理解应该是大量数据预训练的前提，可以把变形的文字也看成一种字体，学习过了就可以准确预测

**Comment by wenlihaoyu** [comment]
> resize到固定尺寸必然会导致文字信息产生变形。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: lywen ***@***.***&gt; 发送时间: 2022年4月9日 21:19 收件人: chineseocr/trocr-chinese ***@***.***&gt; 抄送: archwolf118 ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [chineseocr/trocr-chinese] 现在trocr最大的问题就是这个384*384的预处理 (Issue #3) 为啥不合理？只要你的文本不是太长（比如宽度超过2048）。padding不就浪费了，为啥不选用其他图像侧的backbone呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

形变有啥关系呢，预训练就让模型适应了这样的变化，相当于模型进行了空间映射。

**Comment by archwolf118** [comment]
在ocr文档识别领域，长文本太常见了，32*2000以上的文本经常会出现，resize成方的。我的经验是，即便是目标检测任务，也要padding成方的，模型效果才好，何况变化这么大的文字条了，resize成方的必然会导致信息损失。我来这是探讨改进策略的，并不是质疑您的工作。另外，我上周六早上给您打了10块钱，也感谢了您能开源此工作。

**Comment by wenlihaoyu** [comment]
任何算法都不是全能的。如果觉得此方法不好，可以选择其他算法，不要因为此项目让自己不愉快。

**Comment by archwolf118** [comment]
我是来谈讨改进策略的，一点都没有感到不愉快，比如加入类似swin的结构我们就能取得更好的效果。连此repo的readme都说了，384有待改进。在OCR领域超长文本比比皆是，单纯resize方的，信息必然其损失，空间映射的解释也是有待商榷，我什么我们要从一个超难的出发点去学习呢？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lywen ***@***.***&gt;
发送时间: 2022年4月11日 21:22
收件人: chineseocr/trocr-chinese ***@***.***&gt;
抄送: archwolf118 ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [chineseocr/trocr-chinese] 现在trocr最大的问题就是这个384*384的预处理 (Issue #3)





 
任何算法都不是全能的。如果觉得此方法不好，可以选择其他算法，不要因为此项目让自己不愉快。

**Comment by archwolf118** [comment]
成功修改了输入尺寸，准确率得到了大幅提升。
