### ISSUE TITLE
长文本中相同的文字识别错误，但是切割后都可以识别对

### ISSUE THREAD

**Issue by fourierer** [chineseocr/trocr-chinese#47]
作者您好，非常感谢您的工作，我这边在做一些书籍内容的识别，文本行的宽度基本上都超过了1000像素，用我自己的数据训练之后发现一个非常诡异的问题。
一个文本行中相同的字会出现不同的识别结果，但切割之后都可以识别正确，比如这个样本中有3个“视网膜”关键字，前面和后面识别错误，但是中间的“视网膜”识别正确，如果把3个“视网膜”手动切割开则都可以识别正确，请问可以如何缓解这种情况呢，是因为当前预处理resize成384*384对长文本不太适用还是说跟上下文关系很大？可以提供一些指导性建议么～非常感谢
![25](https://github.com/chineseocr/trocr-chinese/assets/55837279/7a36e21e-7c53-47b1-8268-1005eb33e0ea)

**Comment by fourierer** [comment]
> 作者您好，非常感谢您的工作，我这边在做一些书籍内容的识别，文本行的宽度基本上都超过了1000像素，用我自己的数据训练之后发现一个非常诡异的问题。 一个文本行中相同的字会出现不同的识别结果，但切割之后都可以识别正确，比如这个样本中有3个“视网膜”关键字，前面和后面识别错误，但是中间的“视网膜”识别正确，如果把3个“视网膜”手动切割开则都可以识别正确，请问可以如何缓解这种情况呢，是因为当前预处理resize成384*384对长文本不太适用还是说跟上下文关系很大？可以提供一些指导性建议么～非常感谢 ![25](https://private-user-images.githubusercontent.com/55837279/293154840-7a36e21e-7c53-47b1-8268-1005eb33e0ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyODE1MjksIm5iZiI6MTcwNDI4MTIyOSwicGF0aCI6Ii81NTgzNzI3OS8yOTMxNTQ4NDAtN2EzNmUyMWUtN2M1My00N2IxLTgyNjgtMTAwNWViMzNlMGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDExMjcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1Yzc5OWNhNzExNTdmOTllMjNmNGQ2YzNlNjUxNDc5ZDM4N2M5MDA0ZjBkYjBkZDI4MTYyOTU2MjRiMzljYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gjkuvf9YQzxcwrWjGY26ZMIak9FvTxhy-qHVrN6SBwA)

已经解决，感谢

**Comment by CharmsYANG** [comment]
你好 我也遇到了这个问题 请问是怎么解决的呢

**Comment by fourierer** [comment]
把训练脚本中的no_repeat_ngram_size参数设置成0

**Comment by CharmsYANG** [comment]
感谢 感谢
