### ISSUE TITLE
印章的预训练模型链接失效了，可以再发一下么?

### ISSUE THREAD

**Issue by cqray1990** [chineseocr/trocr-chinese#9]

**Comment by wenlihaoyu** [comment]
目前印章识别需要做一些敏感处理，整理好开放下载，特殊情况下模型会识别解码出客户名称

**Comment by Lanme** [comment]
> 目前印章识别需要做一些敏感处理，整理好开放下载，特殊情况下模型会识别解码出客户名称

请问印章识别近期能开放链接么？

**Comment by Randy-1009** [comment]
> 目前印章识别需要做一些敏感处理，整理好开放下载，特殊情况下模型会识别解码出客户名称

不好意思打扰了，请问近期有提供印章识别模型的安排嘛？
